/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    NavigationMenu: typeof import('./components/layout/NavigationMenu.vue')['default']
    NotFound: typeof import('./components/common/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TokenDisplay: typeof import('./components/business/TokenDisplay.vue')['default']
    UserInfo: typeof import('./components/layout/UserInfo.vue')['default']
  }
}
